import { Command } from "commander";
import { join, resolve } from "node:path";
import {
  getCurrentBranch,
  getRepoRoot,
  requireGitRepo,
  worktreeAdd,
  worktreeList,
  worktreeRemove,
} from "../services/git.ts";
import {
  generateBranchNameWithFallback,
  type AIAttempt,
  type AIAttemptFailure,
} from "../services/ai/index.ts";
import { dryRun, isDryRun } from "../utils/flags.ts";
import { sanitizeForAI } from "../utils/diff.ts";
import { branchToWorktreeDirectoryName, validateBranchName } from "../utils/branch-name.ts";
import {
  confirmOrAbort, jsonOut,
  fail,
  formatAIFallback,
  header,
  p,
  pc,
  promptInput,
  reportAIFailure,
  searchablePicker,
} from "../utils/ui.ts";

export function registerWorktreeCommand(program: Command): void {
  const wt = program
    .command("worktree")
    .alias("wt")
    .description("Isolated worktrees for parallel work, with AI branch naming");

  wt.command("list")
    .alias("ls")
    .description("List all active worktrees")
    .action(async () => {
      header("Git Worktrees");
      if (!(await requireGitRepo())) return;

      const list = await worktreeList();
      if (jsonOut(list)) return;
      if (list.length === 0) {
        p.log.info("No worktrees found.");
        return;
      }

      for (const item of list) {
        const isCurrent = resolve(process.cwd()) === resolve(item.path);
        const prefix = isCurrent ? pc.green("● ") : "  ";
        p.log.message(
          `${prefix}${pc.bold(item.branch)} ${pc.dim(`(${item.head.slice(0, 7)})`)}\n    ${pc.dim(item.path)}`,
        );
      }
      p.outro("Done.");
    });

  wt.command("add [branchOrPrompt]")
    .description("Create a new worktree (accepts branch name or natural language task prompt)")
    .option("-b, --base <branch>", "Base branch to create worktree from")
    .action(async (arg?: string, options?: { base?: string }) => {
      header("Add Worktree");
      if (!(await requireGitRepo())) return;

      let branchName = arg;

      if (!branchName) {
        const input = await promptInput({
          message: "Enter branch name or feature description:",
          placeholder: "e.g. fix/navbar-bug or 'add dark mode toggle'",
          validate: (v) => (!v || !v.trim() ? "Input required" : undefined),
        });

        if (!input) {
          p.cancel("Cancelled.");
          return;
        }
        branchName = input;
      }

      // If the input is already a valid branch name, skip AI entirely. Only
      // treat free-form text (spaces, or long slash-less strings) as natural
      // language that needs an AI suggestion. Dry-run also short-circuits
      // before any network call.
      const looksLikeNaturalLanguage =
        branchName.includes(" ") || (!branchName.includes("/") && branchName.length > 15);

      if (looksLikeNaturalLanguage && !isDryRun()) {
        const s = p.spinner();
        s.start("Generating semantic branch name with AI...");
        try {
          const { result: generated, providerName, model } = await generateBranchNameWithFallback(
            sanitizeForAI(branchName).text,
            undefined,
            (failure: AIAttemptFailure, next?: AIAttempt) => {
              s.message(formatAIFallback(failure, next));
            },
          );
          s.stop(`Branch name generated by ${pc.bold(providerName)} [${pc.cyan(model)}].`);

          const confirmBranch = await promptInput({
            message: "Confirm or edit generated branch name:",
            defaultValue: generated,
            placeholder: generated,
            validate: validateBranchName,
          });

          if (!confirmBranch) {
            p.cancel("Cancelled.");
            return;
          }
          branchName = confirmBranch;
        } catch (err) {
          s.stop(pc.yellow("AI naming failed; formatting the branch name from your text instead."));
          reportAIFailure(err, "Could not generate a branch name with AI:");
          branchName = `feat/${branchName.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 30)}`;
        }
      } else if (looksLikeNaturalLanguage && isDryRun()) {
        // Best-effort slug for the dry-run preview, no AI call.
        branchName = `feat/${branchName.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 30)}`;
      } else {
        const validationError = validateBranchName(branchName);
        if (validationError) {
          fail(validationError);
          return;
        }
      }

      const validationError = validateBranchName(branchName);
      if (validationError) {
        fail(validationError);
        return;
      }

      const sanitizedDir = branchToWorktreeDirectoryName(branchName);
      const repoRoot = await getRepoRoot();
      const targetPath = join(repoRoot, ".worktrees", sanitizedDir);
      const baseBranch = options?.base || (await getCurrentBranch());

      if (dryRun(`create worktree for ${branchName} at ${targetPath} from ${baseBranch}`)) return;

      const s = p.spinner();
      s.start(`Creating worktree for ${pc.cyan(branchName)} at ${pc.dim(targetPath)}...`);

      try {
        const result = await worktreeAdd(branchName, targetPath, baseBranch);
        s.stop(pc.green("Worktree created successfully!"));
        if (result.copiedEnvFiles.length > 0) {
          p.log.info(
            pc.dim(
              `Copied env file(s) from repo root into the worktree: ${result.copiedEnvFiles.join(", ")}`,
            ),
          );
        }
        p.log.message(
          `\nTo switch to your new worktree:\n  ${pc.bold(pc.cyan(`cd ${targetPath}`))}\n`,
        );
        p.outro(pc.green("Ready for isolated development!"));
      } catch (err) {
        s.stop(pc.red("Failed to create worktree."));
        fail(String(err));
      }
    });

  wt.command("remove [target]")
    .alias("rm")
    .description("Remove an active worktree and clean up references")
    .option("-f, --force", "Force remove even with uncommitted changes")
    .option("-y, --yes", "Skip confirmation prompts")
    .action(async (target?: string, options?: { force?: boolean; yes?: boolean }) => {
      header("Remove Worktree");
      if (!(await requireGitRepo())) return;

      const repoRoot = await getRepoRoot();
      const list = await worktreeList();
      const nonMainList = list.filter((w) => !w.isBare && resolve(w.path) !== resolve(repoRoot));

      if (nonMainList.length === 0) {
        p.log.warn("No removable secondary worktrees found.");
        return;
      }

      let selectedPath = target;
      if (selectedPath) {
        const targetPath = selectedPath;
        const match = list.find(
          (w) => w.branch === targetPath || w.path === targetPath || resolve(w.path) === resolve(targetPath),
        );
        if (match) {
          selectedPath = match.path;
        }
        if (resolve(selectedPath) === resolve(repoRoot)) {
          fail("Cannot remove the main repository working tree.");
          return;
        }
      } else {
        const pick = await searchablePicker({
          title: "Select worktree to remove:",
          items: nonMainList.map((w) => ({
            value: w.path,
            label: w.branch,
            hint: w.path,
          })),
          pageSize: 8,
        });

        if (!pick) {
          p.cancel("Cancelled.");
          return;
        }
        selectedPath = pick;
      }

      if (dryRun(`remove worktree ${pc.bold(selectedPath)}`)) return;

      const s = p.spinner();
      s.start(`Removing worktree ${pc.cyan(selectedPath)}...`);

      try {
        await worktreeRemove(selectedPath, options?.force);
        s.stop(pc.green("Worktree removed and references pruned."));
        p.outro("Done.");
      } catch (err: unknown) {
        s.stop(pc.yellow("Worktree removal blocked."));
        const errStr = String(err);
        if (errStr.includes("contains modified or untracked files") || errStr.includes("use --force")) {
          const confirmForce = await confirmOrAbort("Worktree contains untracked build files or local edits. Force remove?", { assumeYes: options?.yes, cancelText: null });

          if (confirmForce) {
            const forceSpinner = p.spinner();
            forceSpinner.start("Force removing worktree...");
            try {
              await worktreeRemove(selectedPath, true);
              forceSpinner.stop(pc.green("Worktree force removed and metadata pruned!"));
              p.outro("Done.");
              return;
            } catch (forceErr) {
              forceSpinner.stop(pc.red("Failed to force remove worktree."));
              fail(String(forceErr));
              return;
            }
          }
        }
        fail(errStr);
      }
    });
}
